youfin_project/youfin_app/urls.py
from django.urls import path
from . import views

app_name = "youfin_app"

urlpatterns = [
    # urls & views bag.back-end
    path('dashboard/', views.dashboard, name='dashboard'),
    # anggaran
    path('anggaran/', views.anggaran, name='anggaran'),
    path('anggaran/tambah/', views.tambah_anggaran, name='tambah_anggaran'),
    path('anggaran/edit/<int:budget_id>/', views.edit_anggaran, name='edit_anggaran'),
    path('anggaran/hapus/<int:budget_id>/', views.hapus_anggaran, name='hapus_anggaran'),
    # transaksi
    path('transaksi/', views.transaksi, name='transaksi'),
    path('transaksi/tambah/', views.tambah_transaksi, name='tambah_transaksi'),
    path('transaksi/edit/<int:transaction_id>/', views.edit_transaksi, name='edit_transaksi'),
    path('transaksi/hapus/<int:transaction_id>/', views.delete_transaksi, name='delete_transaksi'),
    # kategori
    path('kategori/', views.kategori, name='kategori'),
    path('kategori/tambah/', views.tambah_kategori, name='tambah_kategori'),
    path('kategori/edit/<int:category_id>/', views.edit_kategori, name='edit_kategori'),
    path('kategori/hapus/<int:category_id>/', views.hapus_kategori, name='hapus_kategori'),
    # path('notifikasi/', views.notifikasi, name='notifikasi'),
    # path('premium/', views.premium, name='premium'),
    # path('konsultasi/', views.konsultasi, name='konsultasi'),
    path('tips/', views.tips, name='tips'),
    path('pengaturan/', views.pengaturan, name='pengaturan'),
    path('pengaturan/edit/', views.edit_pengaturan, name='edit_pengaturan'),
    path('pengaturan/edit/password', views.ubah_password, name='ubah_password'),
]

youfin_project/youfin_project/urls.py
from django.contrib import admin
from django.urls import path, include
from youfin_app import views

# untuk media, agar dapat menampilkan gambar di web
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('user/login/', views.login_user, name='login'),
    path('user/registrasi/', views.registration_user, name='registration'),
    path('user/page/', include('youfin_app.urls')),
    path('logout/', views.logout_user, name='logout'),
]

# Menambahkan pengaturan untuk melayani file media di semua mode
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

youfin_project/youfin_app/models.py
from django.db import models 
from django.contrib.auth.models import User
from django.db.models import Sum
from django.utils import timezone
from django.utils.timezone import now

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=10, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], blank=True, null=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', null=True, blank=True)

    def __str__(self):
        return self.user.username

    @property
    def is_complete(self):
        """
        Properti untuk mengecek apakah semua data profil terisi dengan lengkap.
        Memeriksa: nomor telepon, alamat, tanggal lahir, jenis kelamin, dan foto profil.
        """
        return all([
            self.phone_number, 
            self.address, 
            self.birth_date, 
            self.gender, 
            self.profile_picture
        ])

    def delete_profile_picture(self):
        """
        Fungsi untuk menghapus foto profil dari server dan mengatur ulang field profile_picture menjadi None.
        """
        if self.profile_picture:
            self.profile_picture.delete(save=False)  # Menghapus file dari media folder
            self.profile_picture = None  # Set field profile_picture ke None
            self.save()  # Menyimpan perubahan ke database


# kategori, anggaran dan transaksi
# Kategori Pengeluaran atau Pemasukan
class Category(models.Model):
    CATEGORY_CHOICES = [
        ('Pemasukan', 'Pemasukan'),
        ('Pengeluaran', 'Pengeluaran'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)  # Menambahkan hubungan ke user
    name = models.CharField(max_length=100)
    category_type = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    total_transactions = models.DecimalField(max_digits=12, decimal_places=2, default=0)  # Field baru untuk menyimpan total transaksi

    def __str__(self):
        return self.name

    def update_total_transactions(self):
        """
        Menghitung dan memperbarui total transaksi untuk kategori ini.
        """
        self.total_transactions = self.transaction_set.aggregate(total=Sum('amount'))['total'] or 0
        self.save()


# Anggaran per Kategori
class Budget(models.Model):
    MONTH_CHOICES = [
        (1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'),
        (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'),
        (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')
    ]

    YEAR_CHOICES = [(r, str(r)) for r in range(2000, now().year + 2)]  # Menambahkan 2 tahun ke depan

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)  # Menambahkan hubungan ke user
    category = models.ForeignKey('Category', on_delete=models.CASCADE)  # Relasi dengan model Category
    bulan = models.IntegerField(choices=MONTH_CHOICES)  # Bulan (default dihapus)
    tahun = models.IntegerField(choices=YEAR_CHOICES)  # Tahun (default dihapus)
    initial_budget = models.DecimalField(max_digits=12, decimal_places=2, default=0)  # Jumlah anggaran awal
    total_expenses = models.DecimalField(max_digits=12, decimal_places=2, default=0)  # Total pengeluaran kategori ini
    remaining_balance = models.DecimalField(max_digits=12, decimal_places=2, default=0)  # Sisa saldo anggaran

    def __str__(self):
        return f"Anggaran {self.category.name} - {self.bulan}/{self.tahun}"
    
    @property
    def spent_percentage(self):
        """
        Mengembalikan persentase pengeluaran dari anggaran.
        Jika lebih dari 100%, batas maksimal 100%.
        """
        if self.initial_budget > 0:
            return min((self.total_expenses / self.initial_budget) * 100, 100)
        return 0

    def update_budget(self):
        """
        Menghitung dan memperbarui total pengeluaran dan sisa saldo untuk anggaran ini.
        """
        # Menghitung total pengeluaran berdasarkan kategori dan periode (bulan dan tahun)
        self.total_expenses = self.category.transaction_set.filter(
            transaction_type='Pengeluaran',
            date__month=self.bulan,
            date__year=self.tahun
        ).aggregate(total=Sum('amount'))['total'] or 0

        # Menghitung sisa saldo
        self.remaining_balance = self.initial_budget - self.total_expenses

        # Menyimpan perubahan
        self.save()
    
    


# Transaksi Pengeluaran atau Pemasukan
class Transaction(models.Model):
    TRANSACTION_CHOICES = [
        ('Pemasukan', 'Pemasukan'),
        ('Pengeluaran', 'Pengeluaran'),
    ]
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)  # Menambahkan hubungan ke user
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_CHOICES)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    date = models.DateField()

    def __str__(self):
        return f'{self.name} - {self.transaction_type}'
    

youfin_project/templates/page/anggaran/edit.html
{% extends 'page/base.html' %}
{% load static %}

{% block title %}Edit Anggaran{% endblock %}

{% block your_content_here %}
<div class="overlap">
    <div class="content-card">
        <h1><i class="bi bi-wallet2" style="margin-right: 4px;"></i> Edit Anggaran</h1>

        <form method="POST">
            {% csrf_token %}

            <!-- Input Kategori (non-editable) -->
            <div class="form-group">
                <label class="my-3" for="category">Kategori:</label>
                <input type="text" id="category" class="form-control" value="{{ budget.category.name }}" readonly>
            </div>

            <!-- Input Bulan -->
            <div class="form-group">
                <label class="my-3" for="bulan">Bulan:</label>
                <select name="bulan" id="bulan" class="form-control" required>
                    {% for value, label in bulan_choices %}
                        <option value="{{ value }}" {% if budget.bulan == value %}selected{% endif %}>
                            {{ label }}
                        </option>
                    {% endfor %}
                </select>
            </div>

            <!-- Input Tahun -->
            <div class="form-group">
                <label class="my-3" for="tahun">Tahun:</label>
                <input type="number" min="2000" max="2100" autocomplete="off" placeholder="Masukan tahun anggaran" name="tahun" id="tahun" class="form-control" value="{{ budget.tahun }}" required>
            </div>

            <!-- Input Anggaran -->
            <div class="form-group">
                <label class="my-3" for="initial_budget">Jumlah Anggaran:</label>
                <input type="number" min="0" autocomplete="off" placeholder="Masukan jumlah anggaran" name="initial_budget" id="initial_budget" class="form-control"
                    value="{{ budget.initial_budget }}" autofocus required>
            </div>

            <button type="submit" class="btn btn-primary mt-3">Simpan</button>
            <a href="{% url 'youfin_app:anggaran' %}" class="btn btn-secondary mt-3">Batal</a>
        </form>
    </div>
</div>
{% endblock %}

youfin_project/templates/page/anggaran/index.html
{% extends 'page/base.html' %}
{% load static %}

{% block title %} Anggaran {% endblock %}

{% block your_content_here %}
<div class="overlap">
    <div class="content-card">
        <h1><i class="bi bi-wallet2" style="margin-right: 4px;"></i> Anggaran</h1>

        <!-- Pesan -->
        <div class="message-box mt-3" id="message-box">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-dismissible fade show {% if message.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}"
                role="alert">
                {{ message }}
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <!-- /Pesan -->

        {% if saldo_bersih > 0 %}
        <a href="{% url 'youfin_app:tambah_anggaran' %}" class="btn btn-primary">Tambah Anggaran</a>
        {% else %}
        <div class="alert alert-warning" role="alert" id="no-category-alert">
            Anda tidak dapat menambahkan anggaran sebelum mencatat pemasukan. Silakan tambahkan transaksi pemasukan
            terlebih dahulu.
        </div>
        <a href="{% url 'youfin_app:transaksi' %}" class="btn btn-primary mb-3">Tambah Transaksi Pemasukan</a>
        {% endif %}

        <!-- Filter Bulan dan Tahun -->
        <form method="GET" class="mt-3">
            <div class="row">
                <!-- Select Bulan -->
                <div class="col-md-3">
                    <select name="bulan" class="form-select" required>
                        <option value="">- Pilih Bulan -</option>
                        {% for choice in bulan_tahun_choices %}
                        <option value="{{ choice.bulan }}">{{ choice.nama_bulan }}
                        </option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Select Tahun -->
                <div class="col-md-3">
                    <select name="tahun" class="form-select" required>
                        <option value="">- Pilih Tahun -</option>
                        {% for year in unique_years %}
                        <option value="{{ year }}">{{ year }}
                        </option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Tombol Filter -->
                <div class="col-md-3">
                    <button type="submit" class="btn btn-primary">
                        <i class="bi bi-funnel"></i> Filter
                    </button>
                    <a href="{% url 'youfin_app:anggaran' %}" class="btn btn-secondary">Reset</a>
                </div>
            </div>
        </form>

        <!-- Alert Pengeluaran Melebihi Anggaran -->
        <div class="alert alert-warning mt-3 alert-negative-balance" id="no-category-alert" style="display: none;"
            role="alert">
            Ada kategori dengan total pengeluaran yang melebihi jumlah anggaran. Harap periksa anggaran Anda!
        </div>

        <!-- Tabel Anggaran -->
        <div class="table-responsive">
            <table class="table mt-3">
                <thead>
                    <tr>
                        <th>Kategori</th>
                        <th>Bulan</th>
                        <th>Tahun</th>
                        <th>Jumlah Anggaran</th>
                        <th>Total Pengeluaran</th>
                        <th>Sisa Saldo</th>
                        <th style="text-align: center;">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for budget in budgets %}
                    <tr>
                        <td>{{ budget.category.name }}</td>
                        <td>{{ budget.get_bulan_display }}</td>
                        <td>{{ budget.tahun }}</td>
                        <td class="budget-value" data-budget="{{ budget.initial_budget }}">
                            Rp {{ budget.initial_budget|floatformat:2 }}
                        </td>
                        <td class="budget-value" data-budget="{{ budget.total_expenses }}">
                            Rp {{ budget.total_expenses|floatformat:2 }}
                        </td>
                        <td class="budget-value" data-budget="{{ budget.remaining_balance }}">
                            Rp {{ budget.remaining_balance|floatformat:2 }}
                        </td>
                        <td>
                            <div class="d-flex flex-row gap-1">
                                <a href="{% url 'youfin_app:edit_anggaran' budget.id %}"
                                    class="btn btn-warning">Edit</a>
                                <button class="btn btn-danger" data-bs-toggle="modal"
                                    data-bs-target="#deleteModal{{ budget.id }}">
                                    Hapus
                                </button>
                            </div>
                            <!-- Modal Hapus -->
                            <div class="modal fade" id="deleteModal{{ budget.id }}" tabindex="-1"
                                aria-labelledby="deleteModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="deleteModalLabel">Konfirmasi Hapus Anggaran</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            Apakah Anda yakin ingin menghapus anggaran untuk kategori
                                            "{{ budget.category.name }}"?
                                        </div>
                                        <div class="modal-footer">
                                            <form action="{% url 'youfin_app:hapus_anggaran' budget.id %}"
                                                method="POST">
                                                {% csrf_token %}
                                                <button type="button" class="btn btn-secondary"
                                                    data-bs-dismiss="modal">Batal</button>
                                                <button type="submit" class="btn btn-danger">Hapus</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="7" style="color: red; text-align: center;">Tidak ada anggaran yang ditemukan.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>
{% endblock %}

{% block script_anggaran %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Ambil bulan dan tahun dari URL
        const urlParams = new URLSearchParams(window.location.search);
        const bulanParam = urlParams.get('bulan');
        const tahunParam = urlParams.get('tahun');

        // Pilih dropdown bulan dan tahun
        const bulanSelect = document.querySelector('select[name="bulan"]');
        const tahunSelect = document.querySelector('select[name="tahun"]');

        // Jika bulan dan tahun ditemukan di URL, pilih yang sesuai
        if (bulanParam) {
            for (let option of bulanSelect.options) {
                if (option.value == bulanParam) {
                    option.selected = true;
                    break;
                }
            }
        }

        if (tahunParam) {
            for (let option of tahunSelect.options) {
                if (option.value == tahunParam) {
                    option.selected = true;
                    break;
                }
            }
        }

        // Format angka menjadi format rupiah dan menambahkan tanda minus jika nilai negatif
        function formatRupiah(angka) {
            var reverse = angka.toString().split('').reverse().join('');
            var ribuan = reverse.match(/\d{1,3}/g);
            ribuan = ribuan.join('.').split('').reverse().join('');

            // Menambahkan tanda minus jika angka negatif
            var isNegative = angka < 0;
            var formatted = 'Rp ' + ribuan;
            return isNegative ? '- ' + formatted : formatted;
        }

        // Menerapkan format rupiah pada elemen budget-value
        document.querySelectorAll('.budget-value').forEach(function (element) {
            var budgetValue = parseFloat(element.getAttribute('data-budget'));
            if (!isNaN(budgetValue)) {
                element.textContent = formatRupiah(budgetValue);

                // Cek jika saldo negatif dan tampilkan alert
                if (budgetValue < 0) {
                    // Tampilkan alert saldo negatif jika ada saldo negatif
                    var negativeBalanceAlert = document.querySelector('.alert-negative-balance');
                    if (negativeBalanceAlert) {
                        negativeBalanceAlert.style.display = 'block';
                    }
                }
            }
        });

        // script untuk alert message
        var alerts = document.querySelectorAll('.alert');
        // Alert untuk kategori kosong tidak dihilangkan
        var noCategoryAlert = document.getElementById('no-category-alert');
        if (noCategoryAlert) {
            noCategoryAlert.classList.add('show');
        }
        alerts.forEach(function (alert) {
            if (!alert.closest('#no-category-alert')) {
                setTimeout(function () {
                    var alertElement = new bootstrap.Alert(alert);
                    alertElement.close();
                }, 3000);
            }
        });
    });
</script>
{% endblock %}

youfin_project/templates/page/anggaran/tambah.html
{% extends 'page/base.html' %}
{% load static %}

{% block title %}Tambah Anggaran{% endblock %}

{% block your_content_here %}
<div class="overlap">
    <div class="content-card">
        <h1><i class="bi bi-wallet2" style="margin-right: 4px;"></i> Tambah Anggaran</h1>

        <!-- Pesan Alert -->
        <div class="message-box mt-3">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-dismissible fade show {% if message.tags == 'error' %}alert-danger{% else %}alert-success{% endif %}"
                role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
        
            {% if total_income == 0 %}
            <div class="alert alert-warning">
                Anda belum memiliki pemasukan. Meskipun demikian, Anda masih dapat menambahkan anggaran.
            </div>
            {% endif %}
        </div>

        {% if categories %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label class="my-3" for="category">Kategori Pengeluaran:</label>
                <select name="category" id="category" class="form-control" autofocus required>
                    <option value="">- Pilih Kategori Pengeluaran -</option>
                    {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label class="my-3" for="bulan">Bulan:</label>
                <select name="bulan" id="bulan" class="form-control" required>
                    {% for key, value in bulan_choices %}
                    <option value="{{ key }}" {% if key == bulan %}selected{% endif %}>{{ value }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label class="my-3" for="tahun">Tahun:</label>
                <select name="tahun" id="tahun" class="form-control" required>
                    {% for year in years %}
                        <option value="{{ year }}">{{ year }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group">
                <label class="my-3" for="initial_budget">Jumlah Anggaran:</label>
                <input type="number" 
                       min="0" 
                       step="0.01" 
                       placeholder="Masukan jumlah anggaran" 
                       autocomplete="off" 
                       name="initial_budget" 
                       id="initial_budget" 
                       class="form-control" 
                       required>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary mt-3">Simpan</button>
                <a href="{% url 'youfin_app:anggaran' %}" class="btn btn-secondary mt-3 ms-2">Batal</a>
            </div>
        </form>
        {% else %}
        <div class="alert alert-warning mt-3" role="alert">
            Anda belum memiliki kategori pengeluaran, atau semua kategori pengeluaran sudah memiliki anggaran. Silakan
            tambahkan kategori pengeluaran baru jika diperlukan.
        </div>
        <div class="d-flex gap-2">
            <a href="{% url 'youfin_app:tambah_kategori' %}" class="btn btn-primary">Tambah Kategori Pengeluaran</a>
            <a href="{% url 'youfin_app:anggaran' %}" class="btn btn-secondary">Batal</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}